// Code generated by Slice Machine. DO NOT EDIT.

import CapabilitiesPreview from './CapabilitiesPreview/index.svelte';
import Checkout from './Checkout/index.svelte';
import ClaritySprint from './ClaritySprint/index.svelte';
import ClientWorkDescriptions from './ClientWorkDescriptions/index.svelte';
import ClientWorkGallery from './ClientWorkGallery/index.svelte';
import ClientWorkHeading from './ClientWorkHeading/index.svelte';
import EmailForm from './EmailForm/index.svelte';
import FounderLetter from './FounderLetter/index.svelte';
import HeadingAndCopy from './HeadingAndCopy/index.svelte';
import Hero from './Hero/index.svelte';
import OurStory from './OurStory/index.svelte';
import PackageCards from './PackageCards/index.svelte';
import PathwaysPreview from './PathwaysPreview/index.svelte';
import PathwaysCards from './PathwaysCards/index.svelte';
import AlternateHero from './AlternateHero/index.svelte';
import RichText from './RichText/index.svelte';
import SelectedPartners from './SelectedPartners/index.svelte';
import SelectedWork from './SelectedWork/index.svelte';
import ToolboxAndCapabilities from './ToolboxAndCapabilities/index.svelte';
import WorkGallery from './WorkGallery/index.svelte';

export const components = {
	capabilities_preview: CapabilitiesPreview,
	checkout: Checkout,
	clarity_sprint: ClaritySprint,
	client_work_descriptions: ClientWorkDescriptions,
	client_work_gallery: ClientWorkGallery,
	client_work_heading: ClientWorkHeading,
	email_form: EmailForm,
	founder_letter: FounderLetter,
	heading_and_copy: HeadingAndCopy,
	hero: Hero,
	our_story: OurStory,
	packages: PackageCards,
	pathways: PathwaysPreview,
	pathways_cards: PathwaysCards,
	pathways_hero: AlternateHero,
	rich_text: RichText,
	selected_partners: SelectedPartners,
	selected_work: SelectedWork,
	toolbox_and_capabilities: ToolboxAndCapabilities,
	work_gallery: WorkGallery
};
